apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  namespace: first-app-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      restartPolicy: Always
      containers:
        - name: second-node
          image: homey/kub-first-app:4
